apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-api
  labels:
    app: demo1-api
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo1-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: demo1-api
    spec:
      containers:
      - image: 879873534644.dkr.ecr.ap-northeast-1.amazonaws.com//eks-test:latest
        imagePullPolicy: Always
        name: demo1-api
        ports:
            - containerPort: 8080
              protocol: TCP
